-- 1. EMPLOYEES Table

CREATE TABLE EMPLOYEES (

    EMP_ID NUMBER PRIMARY KEY,

    EMP_NAME VARCHAR2(100) NOT NULL,

    DEPARTMENT VARCHAR2(50),

    SALARY NUMBER(10, 2),

    STATUS VARCHAR2(10) CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))

);


-- 2. EMP_PERFORMANCE Table

CREATE TABLE EMP_PERFORMANCE (

    PERF_ID NUMBER PRIMARY KEY,

    EMP_ID NUMBER,

    REVIEW_DATE DATE, -- Unique Constraint on EMP_ID and REVIEW_DATE??

    PERF_SCORE NUMBER(1) CHECK (PERF_SCORE BETWEEN 1 AND 5),

    CONSTRAINT fk_emp_perf FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID)

);


-- 3. SALARY_AUDIT Table

CREATE TABLE SALARY_AUDIT (
    AUDIT_ID NUMBER PRIMARY KEY,

    EMP_ID NUMBER,

    OLD_SALARY NUMBER(10, 2),

    NEW_SALARY NUMBER(10, 2),

    CHANGE_DATE DATE,

    REASON VARCHAR2(255)

);