-- Clear tables if re-running

DELETE FROM EMP_PERFORMANCE;

DELETE FROM SALARY_AUDIT;

DELETE FROM EMPLOYEES;


-- --------------------------------------------------------

-- 1. POPULATE EMPLOYEES

-- --------------------------------------------------------


-- IT Department

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPARTMENT, SALARY, STATUS)

VALUES (101, 'Alice Smith', 'IT', 60000, 'ACTIVE');



INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPARTMENT, SALARY, STATUS)

VALUES (102, 'Bob Johnson', 'IT', 55000, 'ACTIVE');



INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPARTMENT, SALARY, STATUS)

VALUES (103, 'Charlie Brown', 'IT', 50000, 'INACTIVE'); -- Should be ignored by Procedure



-- HR Department

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPARTMENT, SALARY, STATUS)

VALUES (104, 'Diana Prince', 'HR', 65000, 'ACTIVE');



INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, DEPARTMENT, SALARY, STATUS)

VALUES (105, 'Evan Wright', 'HR', 62000, 'ACTIVE');





-- --------------------------------------------------------

-- 2. POPULATE EMP_PERFORMANCE

-- --------------------------------------------------------



-- Alice (101): High performer (Avg = 4.75). Will get 15% raise.

INSERT INTO EMP_PERFORMANCE VALUES (1, 101, ADD_MONTHS(SYSDATE, -9), 5);

INSERT INTO EMP_PERFORMANCE VALUES (2, 101, ADD_MONTHS(SYSDATE, -6), 4);

INSERT INTO EMP_PERFORMANCE VALUES (3, 101, ADD_MONTHS(SYSDATE, -3), 5);

INSERT INTO EMP_PERFORMANCE VALUES (4, 101, SYSDATE, 5);



-- Bob (102): Average performer (Avg = 3.0). Will get 8% raise.

-- NOTE: Scores go 4 -> 3 -> 2. This triggers the "Consecutive Decline" for Task 1.

INSERT INTO EMP_PERFORMANCE VALUES (5, 102, ADD_MONTHS(SYSDATE, -9), 4);

INSERT INTO EMP_PERFORMANCE VALUES (6, 102, ADD_MONTHS(SYSDATE, -6), 3);

INSERT INTO EMP_PERFORMANCE VALUES (7, 102, ADD_MONTHS(SYSDATE, -3), 2);

INSERT INTO EMP_PERFORMANCE VALUES (8, 102, SYSDATE, 3);



-- Charlie (103): Inactive.

INSERT INTO EMP_PERFORMANCE VALUES (9, 103, ADD_MONTHS(SYSDATE, -9), 2);

INSERT INTO EMP_PERFORMANCE VALUES (10, 103, ADD_MONTHS(SYSDATE, -6), 2);



-- Diana (104): Low performer (Avg = 2.25). Will get NO raise.

INSERT INTO EMP_PERFORMANCE VALUES (11, 104, ADD_MONTHS(SYSDATE, -9), 3);

INSERT INTO EMP_PERFORMANCE VALUES (12, 104, ADD_MONTHS(SYSDATE, -6), 2);

INSERT INTO EMP_PERFORMANCE VALUES (13, 104, ADD_MONTHS(SYSDATE, -3), 2);

INSERT INTO EMP_PERFORMANCE VALUES (14, 104, SYSDATE, 2);



-- Evan (105): Good performer (Avg = 4.0). Will get 15% raise.

INSERT INTO EMP_PERFORMANCE VALUES (15, 105, ADD_MONTHS(SYSDATE, -9), 4);

INSERT INTO EMP_PERFORMANCE VALUES (16, 105, ADD_MONTHS(SYSDATE, -6), 4);

INSERT INTO EMP_PERFORMANCE VALUES (17, 105, ADD_MONTHS(SYSDATE, -3), 4);

INSERT INTO EMP_PERFORMANCE VALUES (18, 105, SYSDATE, 4);



COMMIT;